select * from customer_table limit 20;
-- - ALTER TABLE customer_table
-- RENAME COLUMN "purchase_amount_(usd)" TO purchase_amount;
-- --Q1. What is the total revenue generated by male vs. female customers?
-- 

-- ALTER TABLE customer_table
-- DROP COLUMN promo_code_used
--  my task is to distribute age into 4 sub columns like young adult,adult, middle agd and senior
-- currently what i have did i divided ages into 4 sub compartments
-- its time to distrurbute in sub parts
-- ALTER TABLE customer_table 
-- ADD COLUMN age_group TEXT;
UPDATE customer_table
SET age_group = CASE t.age_group_bin
    WHEN 1 THEN 'Young Adult'
    WHEN 2 THEN 'Adult'
    WHEN 3 THEN 'Middle-Aged'
    WHEN 4 THEN 'Senior'
END
FROM (
    SELECT customer_id, NTILE(4) OVER (ORDER BY age) AS age_group_bin
    FROM customer_table
) AS t
WHERE customer_table.customer_id = t.customer_id;  
-- ALTER TABLE customer_table
-- ALTER COLUMN purchase_amount TYPE NUMERIC(10,2);
select gender, SUM(purchase_amount) as revenue
from customer_table
group by gender;

-- -- --Q2. Which customers used a discount but still spent more than the average purchase amount?
-- select customer_id ,purchase_amount
-- from customer_table
-- where discount_applied='YES' and purchase_amount>= (select AVG(purchase_amount) from customer_table);
SELECT customer_id, purchase_amount
FROM customer_table
WHERE LOWER(discount_applied) = 'yes'
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM customer_table
  );
-- which are top  5 products with highest average review rating
select item_purchased, ROUND(AVG(review_rating ::numeric),2) as "Average Product Rating"
from customer_table
group by item_purchased
order by avg(review_rating) desc
limit 5;
-- q4. compare the average purchse amount between standard and express shipping
select shipping_type, ROUND(AVG(purchase_amount::numeric),2)
from customer_table
where shipping_type in('Standard','Express')
group by shipping_type;
-- q5 do subscribed customers spend more ? compare average spend and total_revenue
-- between subscribers and non -subscribers
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(AVG(purchase_amount),2) as total_revenue
from customer_table
group by subscription_status
order by total_revenue,avg_spend desc;

-- which 5 products have highest percentage of purchases with discount applied
select item_purchased,
ROUND(100* SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/ COUNT(*) ,2) as discount_rate
from customer_table
group by item_purchased
order by discount_rate desc
limit 5;

-- segment customers into new,returning and loyl based on their total
-- number of previous purchases and show count of each segment
with customer_type as (
select customer_id, previous_purchases,
CASE 
    WHEN previous_purchases =1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer_table
);
select customer_segment, COUNT(*) as "Number of customers"
from customer_type
group by customer_segment;
--q8. what are the top 3 most purchased products within each category
with item_counts as(
select category, item_purchased, COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by COUNT(customer_id) DESC) as item_rank
from customer_table
group by category,item_purchased
)

select item_rank, item_purchased, total_orders
from item_counts
where item_rank<=3 ;

 -- q9. are customer who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
 select subscription_status, count(customer_id) as repeat_buyers
 from customer_table
 where previous_purchases >5
 group by subscription_status;

 -- q10: what is revenue contribution of each age group
 select age_group, SUM(purchase_amount) as total_revenue
 from customer_table
 group by age_group
 order by total_revenue desc;

 select * from customer_table limit 60